config/routes.rb
Myblog::Application.routes.draw do
  resources :comments
  resources :posts
  resources :messages
    

  root :to => 'posts#index'

	  
   resources :posts do
	  resources :comments
   end
   
   match '/about' => 'pages_control#about'
   match '/contactus' => 'pages_control#contactus'
   
   match 'contact' => 'contact#new', :as => 'contact', :via => :get
   match 'contact' => 'contact#create', :as => 'contact', :via => :post

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :name
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :date, :author
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to("/contactus", :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/pages_control_controller.rb
class PagesControlController < ActionController::Base
  layout "application"
  def about
     respond_to do |format|
      format.html # about.html.erb
    end
  end
  
  def contact
     respond_to do |format|
      format.html # contact.html.erb
     end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order('posts.created_at DESC').page(params[:page]).per(5) 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_control_helper.rb
module PagesControlHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-wrapper">
	<div class="comment-title">
	  <%= comment.name %>
	</div>
	 
	<div class="comment-body">
	  <%= comment.body %>
	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Body</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.body %></td>
    <td><%= comment.post %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/contact/new.html.erb
<div class="post-title">Contact Us</div>


<%= form_for @message, :url => contact_path do |form| %>
  <fieldset class="fields">
  	<div> <%= form.label :name %></div>
    <div class="field">
      <%= form.text_field :name %>
    </div>
    
    <div><%= form.label :email %></div>
    <div class="field">
      <%= form.text_field :email %>
    </div>
    <div><%= form.label :subject %></div>
    <div class="field">
      <%= form.text_field :subject %>
    </div>
    <div> <%= form.label :body %></div>
    <div class="field">
      <%= form.text_area :body %>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send" %>
  </fieldset>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catalyst: Student Ministries</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <script type="text/javascript" src="/assets/custom-script.js"></script>
  
 <link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon"/>
<link rel="icon" href="/assets/favicon.ico" type="image/x-icon"/>

</head>
<body>
	<div id="db-top-bar" class="">
  	<div class="top-bar-inner">
  		<div class="top-bar-content">
	  		<div class="social-media-wrapper">
	  			<div class="social-media-inner">
	  				<div class="twitter-icon"><a href="/"><img src="/assets/social-placeholder.png" class="placeholder"></a></div>
	  				<div class="youtube-icon"><a href="/"><img src="/assets/social-placeholder.png" class="placeholder"></a></div>
					<div class="link-icon"><a href="/"><img src="/assets/social-placeholder.png" class="placeholder"></a></div>
	  				<div class="facebook-icon"><a href="/"><img src="/assets/social-placeholder.png" class="placeholder"></a></div>

	  			</div>
	  		</div>
		</div>

  	</div>
  </div>
  
<div id="site-wrapper">
  <div id="db-header">
	
		<div class=" site-logo"><!-- NOTE: any time you see , this element will be hidden from SharePoint dialog windows  -->
			<a href="/"><img style="border-width:0px;" alt="OED Microsite" src="/assets/header-logo.png"></a>	
		</div>
			
	
		<!-- top navigation area -->
		<div class=" top-nav">
			<!-- top navigation publishing data source -->
			
	
			<!-- top navigation menu -->
			<div class="top-nav-inner">
				<div class="menu horizontal menu-horizontal">
					<%= render_navigation %>
				</div>
			</div>	
		</div>
	</div>

	<div id="main-content">
		<div id="main-content-wrapper">
			<div id="leftpanel">
			
			<!-- left navigation -->
			<div class="left-nav-top"></div>
						
				<div class="left-panel-content">
					<div class="left-panel-title">Welcome to our Blog!</div>
					<div class="left-panel-text">This blog is for the CATALYST: Student Ministries orginization at SBTS! Here you will find news, updates, and postings about the activity of our orginization. <br/><br/> Please be sure to check back often as we will be updating it with important information throughout the semester!</div>
					<div class="create-post"><%= link_to 'Create New Post', new_post_path %></div>
				</div>			
			</div>
			
			<div class="content-area">
			<%= yield %>
			</div>
			<div class="lower-bg"></div>
		</div>
		
		<div style="clear: both;" class="s4-notdlg" id="db-footer">
			
			<div class="footer-inner">
				
				<div class="footer-left">
					<div class="footer-logo">
						<img border="0" src="/assets/footer-logo.png"><div class="footer-contact"><span>2825 Lexington Road
						Louisville, KY 40280
						(800) 626-5525</span></div></div>
				</div>
				
				<div class="footer-right">
					<div class="footer-copyright"> 
						 <span class="copyright-text">&copy; 2013 Office of Student Ministries | The Southern Baptist Theological Seminary. <br/>All Rights Reserved. Questions or Comments? Contact our webmaster.</span></div>
				</div>
			</div>
		</div>
	</div>
</div>	
</body>
</html>

app/views/pages/about.html.erb
<div class="about-page">

<h2>About Us</h2>

</div>

app/views/pages/contact.html.erb
<div class="contact-page">

<h2>Contact Us</h2>
</div>

app/views/pages_control/about.html.erb
<div class="about-page">

<div class="post-title">About Us</div>

<div class="about-body">

<p><img class="about-img" src="/assets/logo.png" alt=""/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel justo quis ante dapibus ultricies. Sed est ante, scelerisque et convallis ut, elementum sit amet orci. Sed pellentesque velit justo. Ut bibendum ipsum aliquam dolor tincidunt et tincidunt metus auctor. Proin in volutpat nibh. Phasellus eget est urna. Vestibulum accumsan suscipit dignissim. Integer ultrices dui id magna facilisis tempus. Fusce nec erat nibh. Duis vulputate malesuada velit, quis rhoncus ipsum faucibus a. Integer pellentesque ligula ultricies quam volutpat non condimentum nisi aliquam. Nulla commodo lobortis vulputate.</p>
<br/>
<p>Aenean ultrices condimentum metus, in condimentum nisl consectetur in. Nam ac ante at orci tempor laoreet. Mauris in diam eget velit tempus facilisis. Vivamus feugiat est sit amet sapien egestas convallis. Sed pretium mattis pharetra. In hac habitasse platea dictumst. Nunc luctus mauris vel orci mollis et fringilla erat consequat. Phasellus id dui sit amet quam condimentum scelerisque in viverra lectus.Fusce mollis nibh sit amet lorem viverra ultricies. Curabitur cursus, magna ut condimentum congue, magna justo vehicula justo, dignissim pharetra nisi sapien non urna. Pellentesque in elit et nulla pharetra rhoncus. Mauris congue elementum dolor a euismod. Sed auctor imperdiet placerat. </p>
<br/>
<p>Etiam rutrum ligula nec nisl feugiat in placerat nulla commodo. Nulla facilisi. Duis convallis elit sodales neque pretium congue vulputate libero ornare. Vestibulum euismod felis et purus varius placerat. Phasellus non dui vel massa pharetra rutrum. Nulla a lorem justo, quis bibendum nibh. Nulla tellus lectus, luctus non ultrices sit amet, dignissim vitae diam. Duis cursus dui viverra dolor fringilla accumsan. Nullam rhoncus nisi ut dui luctus vel dignissim tellus venenatis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In porttitor aliquet dolor eget tempor. Curabitur gravida tempor condimentum. Suspendisse at dignissim erat. Sed ut lacus hendrerit nisl facilisis luctus eu vitae nunc. Aliquam dictum pharetra est sit amet mollis. Praesent sodales iaculis dolor nec elementum.</p>
	</div>

</div>

app/views/pages_control/contact.html.erb
<div class="contact-page">

<div class="post-title">Contact Us</div>

<div class="about-body">

<p><img class="about-img" src="/assets/logo.png" alt=""/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel justo quis ante dapibus ultricies. Sed est ante, scelerisque et convallis ut, elementum sit amet orci. Sed pellentesque velit justo. Ut bibendum ipsum aliquam dolor tincidunt et tincidunt metus auctor. Proin in volutpat nibh. Phasellus eget est urna. Vestibulum accumsan suscipit dignissim. Integer ultrices dui id magna facilisis tempus. Fusce nec erat nibh. Duis vulputate malesuada velit, quis rhoncus ipsum faucibus a. Integer pellentesque ligula ultricies quam volutpat non condimentum nisi aliquam. Nulla commodo lobortis vulputate.</p>
<br/>
<p>Aenean ultrices condimentum metus, in condimentum nisl consectetur in. Nam ac ante at orci tempor laoreet. Mauris in diam eget velit tempus facilisis. Vivamus feugiat est sit amet sapien egestas convallis. Sed pretium mattis pharetra. In hac habitasse platea dictumst. Nunc luctus mauris vel orci mollis et fringilla erat consequat. Phasellus id dui sit amet quam condimentum scelerisque in viverra lectus.Fusce mollis nibh sit amet lorem viverra ultricies. Curabitur cursus, magna ut condimentum congue, magna justo vehicula justo, dignissim pharetra nisi sapien non urna. Pellentesque in elit et nulla pharetra rhoncus. Mauris congue elementum dolor a euismod. Sed auctor imperdiet placerat. </p>
<br/>
<p>Etiam rutrum ligula nec nisl feugiat in placerat nulla commodo. Nulla facilisi. Duis convallis elit sodales neque pretium congue vulputate libero ornare. Vestibulum euismod felis et purus varius placerat. Phasellus non dui vel massa pharetra rutrum. Nulla a lorem justo, quis bibendum nibh. Nulla tellus lectus, luctus non ultrices sit amet, dignissim vitae diam. Duis cursus dui viverra dolor fringilla accumsan. Nullam rhoncus nisi ut dui luctus vel dignissim tellus venenatis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In porttitor aliquet dolor eget tempor. Curabitur gravida tempor condimentum. Suspendisse at dignissim erat. Sed ut lacus hendrerit nisl facilisis luctus eu vitae nunc. Aliquam dictum pharetra est sit amet mollis. Praesent sodales iaculis dolor nec elementum.</p>
	</div>
	
</div>

app/views/pages_control/contactus.html.erb
<div class="contact-page">

<div class="post-title">Thank You! Your Email Was Sent Successfully!</div>

<div class="about-body">
	
<p>Hey Jason and Nathan,<br/><br/>
Please use the following gmail login to test the contact form. I set up a new gmail account specifically to test this form. </p><br/>

<b>Username:</b> sbts.ruby.blog@gmail.com<br/>
<b>Password:</b> sbtsrubyblog1!<br/>




	
</div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field edit-title">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field edit-body">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="post-title">Editing post</div>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="post-index-wrapper">
<% @posts.each do |post| %>
<div class="post-wrapper">
    <div class="post-title"><%= link_to post.title, post %></div>
	<div class="post-date"><%= post.created_at.strftime("%m/%d/%Y") %></div>
    <div class="post-body"><%= post.body %></div>
    <div class="post-edit"><%= link_to 'Edit', edit_post_path(post) %> | <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></div>

    
</div>
<% end %>


<br />


<%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="post-title"> Create New Post </div>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="post-wrapper">
	<div class="post-title">
	  <%= @post.title %>
	</div>
	 
	<div class="post-body">
	  <%= @post.body %>
	</div>
	<div class="post-edit"><%= link_to 'Edit Post', edit_post_path(@post) %> | <%= link_to 'Delete', post_path, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Back to Posts', posts_path %> </div>

</div> 
<!-- AddThis Button BEGIN -->
<div class="share-buttons-wrapper">
<div class="addthis_toolbox addthis_default_style">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>
<a class="addthis_button_pinterest_pinit"></a>
<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
<a class="addthis_counter addthis_pill_style"></a>
</div>
</div>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=undefined"></script>
<!-- AddThis Button END -->

<div id="comments-wrapper"> 
<div class="comments-title">Comments Section</div>
<%= render @post.comments %>
 
<div class="add-comment-button"><input type="button" value="Add a Comment" title="Add a Comment" onclick="leftHeight();"></div>

<div class="comment-form">
<%= render "comments/form" %>
</div>
 
</div>
 